frontend:
  hosts:
    - 35.180.182.174
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: omega_frontend_key.pem

backend:
  hosts:
    - 15.237.92.135
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: omega_backend_key.pem

all:
  hosts:
    - 35.180.182.174
    - 15.237.92.135
